blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/slice-soft/ss-gameforge-godot/discussions
    about: Use Discussions for questions, ideas, and general support.
