name: Release Godot Addons

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.event_name == 'push'
    uses: slice-soft/ss-pipeline/.github/workflows/create-release.yml@v0
    secrets: inherit

  release-addons:
    needs: release
    if: needs.release.outputs.releases_created == 'true'
    uses: slice-soft/ss-pipeline/.github/workflows/release-godot-addons.yml@v0
    secrets: inherit

  update-readme-versions:
    needs:
      - release
      - release-addons
    if: needs.release.outputs.releases_created == 'true' && needs.release-addons.result == 'success'
    uses: slice-soft/ss-pipeline/.github/workflows/run-script-and-pr.yml@v0
    secrets:
      token: ${{ secrets.CROSS_REPO_TOKEN_GAMEFORGE }}
    with:
      script-path: scripts/update-readme-versions.sh
      commit-message: "chore(main): update addons table"
      pr-title: "chore(main): update addons table"
      pr-body: "Automated README addon table update after release."
      branch: chore/update-addons-table
      add-paths: |
        README.md
        README.es.md

  update-landing:
    needs:
      - release
      - release-addons
    if: needs.release.outputs.releases_created == 'true' && needs.release-addons.result == 'success'
    uses: slice-soft/ss-pipeline/.github/workflows/run-script-and-pr.yml@v0
    secrets:
      token: ${{ secrets.CROSS_REPO_TOKEN_GAMEFORGE }}
    with:
      repository: slice-soft/ss-landing-gameforge
      script-path: scripts/update-gameforge-versions.sh
      commit-message: "chore(main): update gameforge addon versions"
      pr-title: "chore(main): update gameforge addon versions"
      pr-body: "Automated version update after gameforge release."
      branch: chore/update-gameforge-versions

  update-docs:
    needs:
      - release
      - release-addons
    if: needs.release.outputs.releases_created == 'true' && needs.release-addons.result == 'success'
    uses: slice-soft/ss-pipeline/.github/workflows/run-script-and-pr.yml@v0
    secrets:
      token: ${{ secrets.CROSS_REPO_TOKEN_GAMEFORGE }}
    with:
      repository: slice-soft/ss-docs-gameforge
      script-path: scripts/update-gameforge-versions.sh
      commit-message: "chore(main): update gameforge addon versions"
      pr-title: "chore(main): update gameforge addon versions"
      pr-body: "Automated version update after gameforge release."
      branch: chore/update-gameforge-versions
